### PR TITLE
 Add Diff module and configure it to use admin theme when viewing diffs

### LINKED ISSUE #17: Workflow: Allow editor to see the difference between versions sent for review
As an Editor, I want to see the difference between revisions visually that have been sent for review, so that I can easily see what has changed and approve/reject accordingly.

### PR DESCRIPTION
**Pull request by stephen-cox**
Closes #17

### CODE REVIEW

**Comment by willguv** [comment]
Great to see, thanks @stephen-cox

**Review by finnlewis — COMMENTED** [review]
Works well, look good. Might just want to check the preferred theme for diff with content designers but easy enough to change, also commented on https://github.com/localgovdrupal/localgov_workflows/issues/17

**Review by finnlewis — APPROVED** [review]

**Review by Adnan-cds — APPROVED** [review]
Diff works for me.  Code changes look good.  So I am happy.  Thanks for the change :)

I had to manually enable the localgov_workflows module in a fresh localgov profile install.  But that's expected, right?

**Comment by stephen-cox** [comment]
> I had to manually enable the localgov_workflows module in a fresh localgov profile install. But that's expected, right?

It is. We're not enforcing the workflow, it's there if people want it.

**Comment by Adnan-cds** [comment]
Thanks for the confirmation Steve :)

**Pull request merged**
