### PR TITLE
Ensure last_email_run gets initialized

### LINKED ISSUE #92: [Workflow notifications] Notifications not processed after clean install
Testing a clean install of the `localgov_workflows_notifications` module, we noticed that the hook_cron logic to enqueue entities won't ever run, due to the state variable `localgov_workflows_notifications.last_email_run` not having been initialised.

In the below code, the default value (current request time) will always be before the calculated "next run" time, making the if-condition fail:
```
 $request_time = \Drupal::time()->getRequestTime();
  $last_run = \Drupal::state()->get('localgov_workflows_notifications.last_email_run', $request_time);
  $next_run = $last_run + 86400 * $settings->get('email_frequency');
  if ($request_time >= $next_run) {
```

### Resolutions

#90 suggests that the state would be initialised to the install time of the module - should it do this?

Else, amending the if condition to check for a default value would fix the issue. e.g.:

`  if ($request_time >= $next_run || $request_time == $last_run) { `

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #92

### CODE REVIEW

**Comment by graham-web** [comment]
Minor thought... shouldn't it also reset the `last_email_run` state when the "Enable email notifications" box has become ticked? Else the user would receive a flood of old notifications as soon as they [re-]enable e-mails!

Or perhaps simpler, for the same effect, just update state every time within `hook_cron` during the early-return?

**Comment by ekes** [comment]
> Else the user would receive a flood of old notifications as soon as they [re-]enable e-mails!

Reading the code what gets sent by the module is base on querying using the REQUEST_TIME https://github.com/localgovdrupal/localgov_workflows/blob/94dad592dd71b1496db7f1fa585c15cbf752c610/modules/localgov_workflows_notifications/localgov_workflows_notifications.module#L133 and https://github.com/localgovdrupal/localgov_workflows/blob/94dad592dd71b1496db7f1fa585c15cbf752c610/modules/localgov_workflows_notifications/localgov_workflows_notifications.module#L143 iff the run should happen based on the last run value https://github.com/localgovdrupal/localgov_workflows/blob/94dad592dd71b1496db7f1fa585c15cbf752c610/modules/localgov_workflows_notifications/localgov_workflows_notifications.module#L136

So the number of mails should be the same no matter what?

Ahh https://github.com/localgovdrupal/localgov_workflows/blob/94dad592dd71b1496db7f1fa585c15cbf752c610/modules/localgov_workflows_notifications/localgov_workflows_notifications.module#L142

OK I'd say another issue for that.

**Comment by stephen-cox** [comment]
It's probably a good idea to reset the `last_email_run` state var when turning email sending on.

This would bring in quite a bit of duplication of code when resetting the the var, so I'm thinking of abstracting this into a service to make it easier to test.

Given this is quite critical, I suggest merging this and creating a new issue for reseting the var when enabling email sending.

**Comment by finnlewis** [comment]
Discussed at Merge Tuesday. Thanks for your comment @graham-web - we've created a separate issue to deal with that. https://github.com/localgovdrupal/localgov_workflows/issues/94

Otherwise, we're happy to get this out to councils who are testing.

**Review by finnlewis — APPROVED** [review]

**Pull request merged**
