### PR TITLE
Remove review scheduled transitions when a page is archived

### PR DESCRIPTION
**Pull request by andybroomfield**
Ref #59

Implements the part of delete scheduled transitions by removing the review
scheduled transition from a page that has been archived.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Need to resolve the merge conflict, I assume this is changeing the view title @stephen-cox ?

**Comment by finnlewis** [comment]
@andybroomfield is going to take another look, update the view and pull request then take out of draft when ready.

**Comment by andybroomfield** [comment]
Ready for review now and test added.
This will remove any scheduled review transitions and active reviews for any node that is archived.
Only applies to future nodes as not sure how to do a DB update / clean up for existing ones that have entered review yet, but should stop future ones being set.

**Review by stephen-cox — APPROVED** [review]
Looks good

**Pull request merged**
