### PR TITLE
Add check in hook_install to load the editorial workflow directly fro…

### LINKED ISSUE #2: Throws error when installing module via drush config-import
Hi

I've run into a problem where it throws an error when installing using `drush config-import`. It's fine when enabling the module via the command line `drush en localgovdrupal_workflows`

The error I am getting is
`Import the listed configuration changes? (yes/no) [yes]:
 > 

 [notice] Synchronized extensions: install dynamic_entity_reference.
 [notice] Synchronized extensions: install role_delegation.
 [notice] Synchronized extensions: install localgov_roles.
 [notice] Synchronized extensions: install preview_link.
 [notice] Synchronized extensions: install responsive_preview.
 [notice] Synchronized extensions: install scheduled_transitions.
 [error]  Error: Call to a member function getTypePlugin() on null in localgov_workflows_install() (line 19 of /app/web/modules/contrib/localgov_workflows/localgov_workflows.install) #0 [internal function]: localgov_workflows_install(true)
#1 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('localgov_workfl...', Array)
#2 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(343): Drupal\Core\Extension\ModuleHandler->invoke('localgov_workfl...', 'install', Array)
#3 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(808): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(572): Drupal\Core\Config\ConfigImporter->processExtension('module', 'install', 'localgov_workfl...')
#6 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(509): Drupal\Core\Config\ConfigImporter->processExtensions(Array)
#7 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(336): Drupal\Core\Config\ConfigImporter->doSyncStep('processExtensio...', Array)
#8 /app/vendor/drush/drush/includes/drush.inc(206): Drush\Drupal\Commands\config\ConfigImportCommands->doImport(Object(Drupal\Core\Config\StorageComparer))
#9 /app/vendor/drush/drush/includes/drush.inc(197): drush_call_user_func_array(Array, Array)
#10 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(307): drush_op(Array, Object(Drupal\Core\Config\StorageComparer))
#11 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import(NULL, Array)
#12 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#13 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(311): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#16 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#24 {main}. 
Error: Call to a member function getTypePlugin() on null in /app/web/modules/contrib/localgov_workflows/localgov_workflows.install on line 19 #0 [internal function]: localgov_workflows_install(true)
#1 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('localgov_workfl...', Array)
#2 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(343): Drupal\Core\Extension\ModuleHandler->invoke('localgov_workfl...', 'install', Array)
#3 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(808): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(572): Drupal\Core\Config\ConfigImporter->processExtension('module', 'install', 'localgov_workfl...')
#6 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(509): Drupal\Core\Config\ConfigImporter->processExtensions(Array)
#7 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(336): Drupal\Core\Config\ConfigImporter->doSyncStep('processExtensio...', Array)
#8 /app/vendor/drush/drush/includes/drush.inc(206): Drush\Drupal\Commands\config\ConfigImportCommands->doImport(Object(Drupal\Core\Config\StorageComparer))
#9 /app/vendor/drush/drush/includes/drush.inc(197): drush_call_user_func_array(Array, Array)
#10 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(307): drush_op(Array, Object(Drupal\Core\Config\StorageComparer))
#11 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import(NULL, Array)
#12 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#13 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(311): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#16 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#24 {main}
Error: Call to a member function getTypePlugin() on null in localgov_workflows_install() (line 19 of /app/web/modules/contrib/localgov_workflows/localgov_workflows.install).`

It looks to me like it's expecting the editorial workflow to already be there when it runs the code in the `.install` file.

It could be my mistake of course but I thought I better raise it.

Thanks

### PR DESCRIPTION
**Pull request by finnlewis**
Add check in hook_install to load the editorial workflow directly from config/install if not present. This is to accommodate for installing via drush config-import where sometimes the hook_install is run before the workflow configuration is loaded. See https://github.com/localgovdrupal/localgov_workflows/issues/2 and https://www.drupal.org/project/drupal/issues/2906107

### CODE REVIEW

**Review by stephen-cox — COMMENTED** [review]
There's an `$is_syncing` parameter to `hook_install` (see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Extension!module.api.php/function/hook_install/9.2.x) that could be used if there's no other way around this.

That said the docs say:
> bool $is_syncing: TRUE if the module is being installed as part of a configuration import. In these cases, your hook implementation needs to carefully consider what changes, if any, it should make. For example, it should not make any changes to configuration objects or entities.

We might be fine here as we're creating config entities rather than changing them

**Review by stephen-cox — APPROVED** [review]
Having looked a little further into this I think the general approach is good and solves the issue reported at #2.

**Comment by stephen-cox** [comment]
Realised that we're creating a new editorial workflow rather than loading the existing one if it already exists. Latest commit tries to load the existing editorial workflow configuration, if it already exists.

**Comment by ekes** [comment]
So the issue is that install order can't be guaranteed when using config-import? So hook_install is run before the workflow config is installed. So the advice is not to rely on other configuration in an install hook.

The only other alternative would be to put it somewhere guaranteed to be at the end of the install process? 
But there's no equivalent to post_update. hook_requirements runtime would check too often.

So wracking brain can't think of something better...? Is hook_modules_installed late enough? Or could the config still not be there?

**Review by ekes — APPROVED** [review]
Happy to go with this as the working fix for an immediate blocker; can see if we can make it simpler safer after.

**Pull request merged**
