### PR TITLE
Errors when installing site from existing configuration

### PR DESCRIPTION
**Pull request by Polynya**
Relates to https://github.com/localgovdrupal/localgov_workflows/issues/63

### CODE REVIEW

**Comment by Polynya** [comment]
Relates to https://github.com/localgovdrupal/localgov_workflows/issues/63

**Review by stephen-cox — COMMENTED** [review]
I'm going to need to dig into this further, but initial testing has uncovered some issues.

Site installs from existing config don't work when the LocalGov Demo module is enabled.

Also it doesn't look like the initial config is applied during a site install; content types aren't added to the workflow and scheduled transitions aren't enabled. I suspect this is due to post update hooks not being called in this scenario.

**Comment by Polynya** [comment]
Thanks for investigating this. For me, without LocalGov Demo, when I run site install it adds the correct content types to the workflow and scheduled transitions.

If I install LocalGov Demo, export the config and run site install then I first hit this error:
`Error: Call to a member function setSyncing() on null in Drupal\Core\Config\Entity\ConfigEntityStorage->importDelete()`

This is resolved by the patch here:
https://www.drupal.org/project/drupal/issues/3051453

It doesn't solve the underlying issue, and only continues to more errors e.g.
`Unable to determine class for field type '' found in the 'field.field.' configuration`

**Comment by finnlewis** [comment]
Just looking at this at Merge Monday again. @ekes thinks we do need to incude the hook_install, but we also want to be able to install from existing config, and react differently. We'll need to give more time to this.

**Comment by finnlewis** [comment]
@stephen-cox any chance you can make some time to look at this in more depth?

**Comment by finnlewis** [comment]
Would hook_modules_installed be of use? https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_modules_installed/9.0.x#:~:text=function%20hook_modules_installed&text=Perform%20necessary%20actions%20after%20modules,the%20module%20actually%20being%20installed.

**Comment by stephen-cox** [comment]
Happy to take a look sometime, but might be a while before I get to it.

**Comment by finnlewis** [comment]
Just noting that no one has had time to look at this lately. 

Keen to figure out the best way to support installing from config and everything else!

**Comment by finnlewis** [comment]
@Polynya are you using this branch as a patch at all?

Keen to test it, and resolve the merge conflicts. 

Might you be able to re-create the pull request from a local branch here so we can collaborate on it?

**Comment by finnlewis** [comment]
Actually, I've created a copy here for further testing: https://github.com/localgovdrupal/localgov_workflows/pull/106

**Comment by stephen-cox** [comment]
I'm going to close this as the issue should have been fixed with: https://github.com/localgovdrupal/localgov_workflows/pull/106

Is this is in correct please reopen.

**Pull request closed without merging**
