### PR TITLE
Install contributor role if it doesn't already exist.

### LINKED ISSUE #5: Workflows requires the contributor user which may not be present if localgov_roles module is already enabled
If the roles module was enabled on a site before the latest changes they won't get the new contributor role, but Workflows assumes this role exists.

We should write an update hook to check if the localgov_contributor role exists and, if not, import the configuration for the role.

From discussion on https://github.com/localgovdrupal/localgov_core/issues/115

### PR DESCRIPTION
**Pull request by stephen-cox**
Added update hook to install contributor role if it doesn't already exists

Closes #5

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Steve,
Thanks for this change.  I have test it and may have spotted two issues:
- I deleted the Contributor role from a fresh localgov install and enabled the localgov_workflows module.  The Contributor role didn't come back.
- I reset the update hook number for localgov_workflows (i.e. ```drush php-eval Drupal::keyValue("system.schema")->set("localgov_workflows", 9000)'```) and followed by a ```drush --yes updatedb``` and this time the Contributor role showed up.

So this change clearly works on a site where localgov_workflows is already installed but perhaps not on sites which never installed localgov_workflows.  This may be a nonissue given that every LocalGov site probably already have the localgov_workflows module installed, right?

After doing ```drush updatedb```, I exported the config and noticed that the exported *user.role.localgov_contributor.yml* file is missing the UUID property.  This may be an issue given that other role config files do have a UUID (and also the _core) property :(

**Comment by stephen-cox** [comment]
Thanks for taking a look @Adnan-cds 

I should have fixed both issue.
- There's now a check to ensure that the contributor role exists when installing the workflow module - this could have happened if roles was enabled before the recent update but workflows wasn't.
- A UUID is added when creating the contributor configuration

**Review by Adnan-cds — APPROVED** [review]
Works for me, thanks.

I had a feeling I have had to deal with similar type of code somewhere.  Eventually found it in the [localgov_directories module](https://github.com/localgovdrupal/localgov_directories/blob/9289ec8b3995df8ce032f1bc16d0ff696347a74b/localgov_directories.module#L347) :)

**Comment by stephen-cox** [comment]
Thanks @Adnan-cds for the pointer the where we're doing this already. I realised it's better to use create the user role with

```
\Drupal::entityTypeManager()->getStorage('user_role')
  ->create($contributor_config)
  ->save();
```

as this adds the UUID without needing to do it manually.

**Comment by Adnan-cds** [comment]
Thanks Steve.  Feel free to merge.

**Pull request merged**
